<div class="page-header">
    <h1>Roles (Perfiles) del Sistema</h1>
</div>
<?php View::content() ?>
<?php
    $dt = new DataTable($roles);
    $dt->addHeaders('id', 'Rol', 'plantilla a usar', 'Estado', 'Editar', 'Eliminar');
    $dt->addFields('id', 'rol', 'plantilla');
    $dt->imgLink('figuras/circulo_rojo.png|figuras/circulo_verde.png',
            'admin/roles/activar|admin/roles/desactivar', '', 'activo');
    $dt->imgLink('figuras/editar.png', 'admin/roles/editar');
    $dt->imgLinkConfirm('figuras/eliminar.png', 'admin/roles/eliminar', '', '¿Realmente desea Eliminar Este Rol?');
    echo $dt->render('class="table table-bordered table-striped"');
?>
<div class="form-actions">
    <?php echo Html::linkAction("crear", 'Crear Rol', 'class="btn btn-primary"') ?>
</div>
