<div class="page-header">
    <h1>Recursos del Sistema
        <?php echo Html::linkAction('escaner', 'Escanear Recursos por Agregar', 'class="btn btn-primary pull-right"') ?>
    </h1>
</div>
<?php View::content() ?>
<?php
        $dt = new DataTable($recursos);
        $dt->addHeaders('id', 'Modulo', 'Controlador');
        $dt->addHeaders('Acción', 'Descripción', 'Estado');
        $dt->addHeaders('Editar', 'Eliminar');
        $dt->addFields('id', 'modulo', 'controlador');
        $dt->addFields('accion', 'descripcion');
        $dt->imgLink('figuras/circulo_rojo.png|figuras/circulo_verde.png',
                'admin/recursos/activar|admin/recursos/desactivar', '', 'activo');
        $dt->imgLink('figuras/editar.png', 'admin/recursos/editar');
        $dt->imgLinkConfirm('figuras/eliminar.png', 'admin/recursos/eliminar', '', '¿Realmente desea Eliminar Este Recurso?');
        echo $dt->render('class="table table-bordered table-striped"');
?>
        <div class="form-actions">
    <?php echo Html::linkAction("crear", 'Crear Recurso', 'class="btn btn-primary"') ?>
</div>