<?php $res = Load::model('usuarios')->find('limit: 8', 'order: id DESC'); ?>
<?php $actual = Form::getFieldValue('usuario.id') //vriable con el id del registro que se edita ?>

<ul class="nav nav-tabs nav-stacked">
    <li class="<?php if (!$actual) echo 'active'; ?>">
        <?php echo Html::linkAction("crear", 'Agregar Nuevo'); ?>
    </li>
    <?php foreach ($res as $e): ?>
        <li class="<?php if ($e->id == $actual) echo 'active'; ?>">
            <?php $content = h(strtoupper($e->login)); ?>
            <?php $content .= "<h6>" . (strlen($e->nombres) > 25 ? substr($e->nombres, 0, 25) . '...' : $e->nombres) . "</h6>" ?>
            <?php echo Html::linkAction("editar/$e->id", $content); ?>
        </li>
    <?php endforeach; ?>
    <li>
        <?php echo Html::linkAction("", 'Ver Todos...'); ?>
    </li>
</ul>