<div id='cabecera' class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="brand">Modulo de Administracion</a>
            <div class="nav-collapse pull-right">
                <?php View::renderMenu() ?>
            </div>
            <ul class="secondary-nav" data-dropdown="true">
                <li>
                    <a class="dropdown-toggle" href="#" style="text-transform: capitalize;">
                        <?php echo Auth::get('nombres') ?>
                    </a>
                    <ul class="dropdown-menu">
                        <li><?php echo Html::link('admin/index/logout', 'Salir') ?></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</div>