<!DOCTYPE html>
<html lang="es">
 <head>
	<meta http-equiv='Content-type' content='text/html; charset=<?php echo APP_CHARSET ?>' />
	<title>KumbiaPHP web &amp; App Framework &amp; BackBone.js</title>
     <?php Tag::css('backend/bootstrap.min');
        Tag::css('backend/bootstrap-responsive.min');
       echo Html::includeCss();
      ?>

</head>
<body>
	<header class="page-header">
            <?php echo Html::link('', '<h1>Administrador de Libros</h1>', 'class="brand"') ?>
	
	</header>
        <?php View::content(); ?>
	<footer>Copyrigth Alberto Berroteran 2012</footer>
</body>
</html>
