<div class="page-header">
    <h1>Usuarios del Sistema</h1>
</div>
<div id="mensajes_flash" >        
    <?php View::content() ?>
</div> 
<?php
    $dt = new DataTable($usuarios);
    $dt->addHeaders('id', 'Login', 'Nombres', 'Correo Electronico', 'Estado', 'Editar');
    $dt->addFields('id', 'login', 'nombres', 'email');
    $dt->imgLink('figuras/circulo_rojo.png|figuras/circulo_verde.png',
            'admin/usuarios/activar|admin/usuarios/desactivar', '', 'activo');
    $dt->imgLink('figuras/editar.png', 'admin/usuarios/editar');
    echo $dt->render('class="table table-bordered table-striped"');
?>
    <div class="form-actions">
    <?php echo Html::linkAction("crear", 'Crear Usuario', 'class="btn btn-primary"') ?>
</div>

<?php //View::partial('backend/ultimos_log', FALSE, array('tabla' => 'usuarios')) ?>