<form id="data" class="form-horizontal">
<label for="id">id</label>
<div class="input">
<input type="text" placeholder="id" id="id" readonly value="<%=id%>"/> 
</div>
<label for="author">Autor</label>
<input type="text" placeholder="Autor" id="author" value="<%=author%>"/> 
<label for="title">Título</label>
<input type="text" placeholder="Titulo" id="title" value="<%=title%>"/>
<div class="btn-group">
	<button class="save btn btn-primary" type="button">
		<span class="icon-ok  icon-white"></span>
		Save</button>
	<% if(id) { %>
	<button class="delete btn btn-danger" type="button">
		<span class=" icon-trash  icon-white"></span>
		Delete</button>
	<%}%>
			
</div>
</form>
