<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset='<?php echo APP_CHARSET ?>' />
        <title><?php echo Config::get('config.application.name') ?></title>
        <?php View::partial('backend/css') ?>
        <?php View::partial('backend/js') ?>
    </head>
    <body>
        <?php View::partial('backend/cabecera_app') ?>
        <div class="container">
            <div id="contenido" class="content">
                <?php View::content() ?>
            </div>
            <?php View::partial('backend/pie') ?>
        </div>
    </body>
</html>
